// Tailwind config for the CDN build. Loaded before the Tailwind script runs.
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#242940",
        "on-surface": "#ffffff",
        "inverse-surface": "#e0e1f5",
        "tertiary-container": "#8582ff",
        "surface-dim": "#1a1f33",
        background: "#171b2e",
        "primary-container": "#8083ff",
        "on-secondary-fixed-variant": "#004c69",
        outline: "#b4b3c6",
        "surface-tint": "#c0c1ff",
        "secondary-fixed-dim": "#7bd0ff",
        "outline-variant": "#5c5b6e",
        "on-tertiary-fixed-variant": "#3323cc",
        "on-tertiary-fixed": "#0f0069",
        surface: "#171b2e",
        "on-secondary-fixed": "#001e2c",
        "on-secondary": "#00354a",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-container": "#2a3049",
        "secondary-fixed": "#c4e7ff",
        "surface-variant": "#414560",
        primary: "#c0c1ff",
        "inverse-primary": "#494bd6",
        secondary: "#7bd0ff",
        "on-primary-fixed": "#07006c",
        "on-secondary-container": "#00374d",
        "error-container": "#93000a",
        "surface-bright": "#454a66",
        "tertiary-fixed": "#e2dfff",
        "on-surface-variant": "#e8e6f5",
        "primary-fixed": "#e1e0ff",
        "surface-container-highest": "#414560",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#1d00a5",
        "on-background": "#ffffff",
        error: "#ffb4ab",
        "primary-fixed-dim": "#c0c1ff",
        "on-tertiary-container": "#180092",
        "on-error": "#690005",
        "surface-container-lowest": "#12162599",
        "inverse-on-surface": "#2d303e",
        "secondary-container": "#00a6e0",
        "on-primary": "#1000a9",
        tertiary: "#d3d1ff",
        "on-primary-container": "#ffffff",
        "tertiary-fixed-dim": "#c3c0ff",
        "surface-container-high": "#363b56",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "gutter-lg": "1.5rem",
        "space-md": "0.75rem",
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-lg": "1rem",
        "margin-desktop": "3rem",
        "space-sm": "0.5rem",
        margin: "1.5rem",
        "gutter-sm": "0.75rem",
        "space-xl": "1.75rem",
        gutter: "1rem",
      },
      fontFamily: {
        "technical-code": ["JetBrains Mono", "monospace"],
        display: ["Plus Jakarta Sans", "Geist", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "metric-num": ["Geist", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "Geist", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "display-mobile": ["Plus Jakarta Sans", "Geist", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "Geist", "sans-serif"],
      },
      fontSize: {
        "technical-code": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        display: ["44px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-sm": ["17px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "metric-num": ["26px", { lineHeight: "30px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-caps": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "display-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
};
